/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Choice
 */
export interface Choice {
    /**
     * 
     * @type {number}
     * @memberof Choice
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Choice
     */
    choiceText: string;
    /**
     * 
     * @type {number}
     * @memberof Choice
     */
    votes?: number;
}

/**
 * Check if a given object implements the Choice interface.
 */
export function instanceOfChoice(value: object): value is Choice {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('choiceText' in value) || value['choiceText'] === undefined) return false;
    return true;
}

export function ChoiceFromJSON(json: any): Choice {
    return ChoiceFromJSONTyped(json, false);
}

export function ChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Choice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'choiceText': json['choice_text'],
        'votes': json['votes'] == null ? undefined : json['votes'],
    };
}

export function ChoiceToJSON(value?: Omit<Choice, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'choice_text': value['choiceText'],
        'votes': value['votes'],
    };
}

