/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `abap` - ABAP
 * * `abnf` - ABNF
 * * `actionscript` - ActionScript
 * * `actionscript3` - ActionScript 3
 * * `ada` - Ada
 * * `adl` - ADL
 * * `agda` - Agda
 * * `aheui` - Aheui
 * * `alloy` - Alloy
 * * `ambienttalk` - AmbientTalk
 * * `amdgpu` - AMDGPU
 * * `ampl` - Ampl
 * * `androidbp` - Soong
 * * `ansys` - ANSYS parametric design language
 * * `antlr` - ANTLR
 * * `antlr-actionscript` - ANTLR With ActionScript Target
 * * `antlr-cpp` - ANTLR With CPP Target
 * * `antlr-csharp` - ANTLR With C# Target
 * * `antlr-java` - ANTLR With Java Target
 * * `antlr-objc` - ANTLR With ObjectiveC Target
 * * `antlr-perl` - ANTLR With Perl Target
 * * `antlr-python` - ANTLR With Python Target
 * * `antlr-ruby` - ANTLR With Ruby Target
 * * `apacheconf` - ApacheConf
 * * `apl` - APL
 * * `applescript` - AppleScript
 * * `arduino` - Arduino
 * * `arrow` - Arrow
 * * `arturo` - Arturo
 * * `asc` - ASCII armored
 * * `asn1` - ASN.1
 * * `aspectj` - AspectJ
 * * `aspx-cs` - aspx-cs
 * * `aspx-vb` - aspx-vb
 * * `asymptote` - Asymptote
 * * `augeas` - Augeas
 * * `autohotkey` - autohotkey
 * * `autoit` - AutoIt
 * * `awk` - Awk
 * * `bare` - BARE
 * * `basemake` - Base Makefile
 * * `bash` - Bash
 * * `batch` - Batchfile
 * * `bbcbasic` - BBC Basic
 * * `bbcode` - BBCode
 * * `bc` - BC
 * * `bdd` - Bdd
 * * `befunge` - Befunge
 * * `berry` - Berry
 * * `bibtex` - BibTeX
 * * `blitzbasic` - BlitzBasic
 * * `blitzmax` - BlitzMax
 * * `blueprint` - Blueprint
 * * `bnf` - BNF
 * * `boa` - Boa
 * * `boo` - Boo
 * * `boogie` - Boogie
 * * `bqn` - BQN
 * * `brainfuck` - Brainfuck
 * * `bst` - BST
 * * `bugs` - BUGS
 * * `c` - C
 * * `c-objdump` - c-objdump
 * * `ca65` - ca65 assembler
 * * `cadl` - cADL
 * * `camkes` - CAmkES
 * * `capdl` - CapDL
 * * `capnp` - Cap'n Proto
 * * `carbon` - Carbon
 * * `cbmbas` - CBM BASIC V2
 * * `cddl` - CDDL
 * * `ceylon` - Ceylon
 * * `cfc` - Coldfusion CFC
 * * `cfengine3` - CFEngine3
 * * `cfm` - Coldfusion HTML
 * * `cfs` - cfstatement
 * * `chaiscript` - ChaiScript
 * * `chapel` - Chapel
 * * `charmci` - Charmci
 * * `cheetah` - Cheetah
 * * `cirru` - Cirru
 * * `clay` - Clay
 * * `clean` - Clean
 * * `clojure` - Clojure
 * * `clojurescript` - ClojureScript
 * * `cmake` - CMake
 * * `cobol` - COBOL
 * * `cobolfree` - COBOLFree
 * * `coffeescript` - CoffeeScript
 * * `comal` - COMAL-80
 * * `common-lisp` - Common Lisp
 * * `componentpascal` - Component Pascal
 * * `console` - Bash Session
 * * `coq` - Coq
 * * `cplint` - cplint
 * * `cpp` - C++
 * * `cpp-objdump` - cpp-objdump
 * * `cpsa` - CPSA
 * * `cr` - Crystal
 * * `crmsh` - Crmsh
 * * `croc` - Croc
 * * `cryptol` - Cryptol
 * * `csharp` - C#
 * * `csound` - Csound Orchestra
 * * `csound-document` - Csound Document
 * * `csound-score` - Csound Score
 * * `css` - CSS
 * * `css+django` - CSS+Django/Jinja
 * * `css+genshitext` - CSS+Genshi Text
 * * `css+lasso` - CSS+Lasso
 * * `css+mako` - CSS+Mako
 * * `css+mozpreproc` - CSS+mozpreproc
 * * `css+myghty` - CSS+Myghty
 * * `css+php` - CSS+PHP
 * * `css+ruby` - CSS+Ruby
 * * `css+smarty` - CSS+Smarty
 * * `css+ul4` - CSS+UL4
 * * `cuda` - CUDA
 * * `cypher` - Cypher
 * * `cython` - Cython
 * * `d` - D
 * * `d-objdump` - d-objdump
 * * `dart` - Dart
 * * `dasm16` - DASM16
 * * `dax` - Dax
 * * `debcontrol` - Debian Control file
 * * `debsources` - Debian Sourcelist
 * * `delphi` - Delphi
 * * `desktop` - Desktop file
 * * `devicetree` - Devicetree
 * * `dg` - dg
 * * `diff` - Diff
 * * `django` - Django/Jinja
 * * `docker` - Docker
 * * `doscon` - MSDOS Session
 * * `dpatch` - Darcs Patch
 * * `dtd` - DTD
 * * `duel` - Duel
 * * `dylan` - Dylan
 * * `dylan-console` - Dylan session
 * * `dylan-lid` - DylanLID
 * * `earl-grey` - Earl Grey
 * * `easytrieve` - Easytrieve
 * * `ebnf` - EBNF
 * * `ec` - eC
 * * `ecl` - ECL
 * * `eiffel` - Eiffel
 * * `elixir` - Elixir
 * * `elm` - Elm
 * * `elpi` - Elpi
 * * `emacs-lisp` - EmacsLisp
 * * `email` - E-mail
 * * `erb` - ERB
 * * `erl` - Erlang erl session
 * * `erlang` - Erlang
 * * `evoque` - Evoque
 * * `execline` - execline
 * * `extempore` - xtlang
 * * `ezhil` - Ezhil
 * * `factor` - Factor
 * * `fan` - Fantom
 * * `fancy` - Fancy
 * * `felix` - Felix
 * * `fennel` - Fennel
 * * `fift` - Fift
 * * `fish` - Fish
 * * `flatline` - Flatline
 * * `floscript` - FloScript
 * * `forth` - Forth
 * * `fortran` - Fortran
 * * `fortranfixed` - FortranFixed
 * * `foxpro` - FoxPro
 * * `freefem` - Freefem
 * * `fsharp` - F#
 * * `fstar` - FStar
 * * `func` - FunC
 * * `futhark` - Futhark
 * * `gap` - GAP
 * * `gap-console` - GAP session
 * * `gas` - GAS
 * * `gcode` - g-code
 * * `gdscript` - GDScript
 * * `genshi` - Genshi
 * * `genshitext` - Genshi Text
 * * `gherkin` - Gherkin
 * * `glsl` - GLSL
 * * `gnuplot` - Gnuplot
 * * `go` - Go
 * * `golo` - Golo
 * * `gooddata-cl` - GoodData-CL
 * * `gosu` - Gosu
 * * `graphql` - GraphQL
 * * `graphviz` - Graphviz
 * * `groff` - Groff
 * * `groovy` - Groovy
 * * `gsql` - GSQL
 * * `gst` - Gosu Template
 * * `haml` - Haml
 * * `handlebars` - Handlebars
 * * `haskell` - Haskell
 * * `haxe` - Haxe
 * * `haxeml` - Hxml
 * * `hexdump` - Hexdump
 * * `hlsl` - HLSL
 * * `hsail` - HSAIL
 * * `hspec` - Hspec
 * * `html` - HTML
 * * `html+cheetah` - HTML+Cheetah
 * * `html+django` - HTML+Django/Jinja
 * * `html+evoque` - HTML+Evoque
 * * `html+genshi` - HTML+Genshi
 * * `html+handlebars` - HTML+Handlebars
 * * `html+lasso` - HTML+Lasso
 * * `html+mako` - HTML+Mako
 * * `html+myghty` - HTML+Myghty
 * * `html+ng2` - HTML + Angular2
 * * `html+php` - HTML+PHP
 * * `html+smarty` - HTML+Smarty
 * * `html+twig` - HTML+Twig
 * * `html+ul4` - HTML+UL4
 * * `html+velocity` - HTML+Velocity
 * * `http` - HTTP
 * * `hybris` - Hybris
 * * `hylang` - Hy
 * * `i6t` - Inform 6 template
 * * `icon` - Icon
 * * `idl` - IDL
 * * `idris` - Idris
 * * `iex` - Elixir iex session
 * * `igor` - Igor
 * * `inform6` - Inform 6
 * * `inform7` - Inform 7
 * * `ini` - INI
 * * `io` - Io
 * * `ioke` - Ioke
 * * `irc` - IRC logs
 * * `isabelle` - Isabelle
 * * `j` - J
 * * `jags` - JAGS
 * * `janet` - Janet
 * * `jasmin` - Jasmin
 * * `java` - Java
 * * `javascript` - JavaScript
 * * `javascript+cheetah` - JavaScript+Cheetah
 * * `javascript+django` - JavaScript+Django/Jinja
 * * `javascript+lasso` - JavaScript+Lasso
 * * `javascript+mako` - JavaScript+Mako
 * * `javascript+mozpreproc` - Javascript+mozpreproc
 * * `javascript+myghty` - JavaScript+Myghty
 * * `javascript+php` - JavaScript+PHP
 * * `javascript+ruby` - JavaScript+Ruby
 * * `javascript+smarty` - JavaScript+Smarty
 * * `jcl` - JCL
 * * `jlcon` - Julia console
 * * `jmespath` - JMESPath
 * * `js+genshitext` - JavaScript+Genshi Text
 * * `js+ul4` - Javascript+UL4
 * * `jsgf` - JSGF
 * * `jslt` - JSLT
 * * `json` - JSON
 * * `jsonld` - JSON-LD
 * * `jsonnet` - Jsonnet
 * * `jsp` - Java Server Page
 * * `jsx` - JSX
 * * `julia` - Julia
 * * `juttle` - Juttle
 * * `k` - K
 * * `kal` - Kal
 * * `kconfig` - Kconfig
 * * `kmsg` - Kernel log
 * * `koka` - Koka
 * * `kotlin` - Kotlin
 * * `kql` - Kusto
 * * `kuin` - Kuin
 * * `lasso` - Lasso
 * * `ldapconf` - LDAP configuration file
 * * `ldif` - LDIF
 * * `lean` - Lean
 * * `lean4` - Lean4
 * * `less` - LessCss
 * * `lighttpd` - Lighttpd configuration file
 * * `lilypond` - LilyPond
 * * `limbo` - Limbo
 * * `liquid` - liquid
 * * `literate-agda` - Literate Agda
 * * `literate-cryptol` - Literate Cryptol
 * * `literate-haskell` - Literate Haskell
 * * `literate-idris` - Literate Idris
 * * `livescript` - LiveScript
 * * `llvm` - LLVM
 * * `llvm-mir` - LLVM-MIR
 * * `llvm-mir-body` - LLVM-MIR Body
 * * `logos` - Logos
 * * `logtalk` - Logtalk
 * * `lsl` - LSL
 * * `lua` - Lua
 * * `luau` - Luau
 * * `macaulay2` - Macaulay2
 * * `make` - Makefile
 * * `mako` - Mako
 * * `maql` - MAQL
 * * `markdown` - Markdown
 * * `mask` - Mask
 * * `mason` - Mason
 * * `mathematica` - Mathematica
 * * `matlab` - Matlab
 * * `matlabsession` - Matlab session
 * * `maxima` - Maxima
 * * `mcfunction` - MCFunction
 * * `mcschema` - MCSchema
 * * `meson` - Meson
 * * `mime` - MIME
 * * `minid` - MiniD
 * * `miniscript` - MiniScript
 * * `mips` - MIPS
 * * `modelica` - Modelica
 * * `modula2` - Modula-2
 * * `mojo` - Mojo
 * * `monkey` - Monkey
 * * `monte` - Monte
 * * `moocode` - MOOCode
 * * `moonscript` - MoonScript
 * * `mosel` - Mosel
 * * `mozhashpreproc` - mozhashpreproc
 * * `mozpercentpreproc` - mozpercentpreproc
 * * `mql` - MQL
 * * `mscgen` - Mscgen
 * * `mupad` - MuPAD
 * * `mxml` - MXML
 * * `myghty` - Myghty
 * * `mysql` - MySQL
 * * `nasm` - NASM
 * * `ncl` - NCL
 * * `nemerle` - Nemerle
 * * `nesc` - nesC
 * * `nestedtext` - NestedText
 * * `newlisp` - NewLisp
 * * `newspeak` - Newspeak
 * * `ng2` - Angular2
 * * `nginx` - Nginx configuration file
 * * `nimrod` - Nimrod
 * * `nit` - Nit
 * * `nixos` - Nix
 * * `nodejsrepl` - Node.js REPL console session
 * * `notmuch` - Notmuch
 * * `nsis` - NSIS
 * * `numpy` - NumPy
 * * `nusmv` - NuSMV
 * * `objdump` - objdump
 * * `objdump-nasm` - objdump-nasm
 * * `objective-c` - Objective-C
 * * `objective-c++` - Objective-C++
 * * `objective-j` - Objective-J
 * * `ocaml` - OCaml
 * * `octave` - Octave
 * * `odin` - ODIN
 * * `omg-idl` - OMG Interface Definition Language
 * * `ooc` - Ooc
 * * `opa` - Opa
 * * `openedge` - OpenEdge ABL
 * * `openscad` - OpenSCAD
 * * `org` - Org Mode
 * * `output` - Text output
 * * `pacmanconf` - PacmanConf
 * * `pan` - Pan
 * * `parasail` - ParaSail
 * * `pawn` - Pawn
 * * `peg` - PEG
 * * `perl` - Perl
 * * `perl6` - Perl6
 * * `phix` - Phix
 * * `php` - PHP
 * * `pig` - Pig
 * * `pike` - Pike
 * * `pkgconfig` - PkgConfig
 * * `plpgsql` - PL/pgSQL
 * * `pointless` - Pointless
 * * `pony` - Pony
 * * `portugol` - Portugol
 * * `postgres-explain` - PostgreSQL EXPLAIN dialect
 * * `postgresql` - PostgreSQL SQL dialect
 * * `postscript` - PostScript
 * * `pot` - Gettext Catalog
 * * `pov` - POVRay
 * * `powershell` - PowerShell
 * * `praat` - Praat
 * * `procfile` - Procfile
 * * `prolog` - Prolog
 * * `promela` - Promela
 * * `promql` - PromQL
 * * `properties` - Properties
 * * `protobuf` - Protocol Buffer
 * * `prql` - PRQL
 * * `psql` - PostgreSQL console (psql)
 * * `psysh` - PsySH console session for PHP
 * * `ptx` - PTX
 * * `pug` - Pug
 * * `puppet` - Puppet
 * * `pwsh-session` - PowerShell Session
 * * `py+ul4` - Python+UL4
 * * `py2tb` - Python 2.x Traceback
 * * `pycon` - Python console session
 * * `pypylog` - PyPy Log
 * * `pytb` - Python Traceback
 * * `python` - Python
 * * `python2` - Python 2.x
 * * `q` - Q
 * * `qbasic` - QBasic
 * * `qlik` - Qlik
 * * `qml` - QML
 * * `qvto` - QVTO
 * * `racket` - Racket
 * * `ragel` - Ragel
 * * `ragel-c` - Ragel in C Host
 * * `ragel-cpp` - Ragel in CPP Host
 * * `ragel-d` - Ragel in D Host
 * * `ragel-em` - Embedded Ragel
 * * `ragel-java` - Ragel in Java Host
 * * `ragel-objc` - Ragel in Objective C Host
 * * `ragel-ruby` - Ragel in Ruby Host
 * * `rbcon` - Ruby irb session
 * * `rconsole` - RConsole
 * * `rd` - Rd
 * * `reasonml` - ReasonML
 * * `rebol` - REBOL
 * * `red` - Red
 * * `redcode` - Redcode
 * * `registry` - reg
 * * `resourcebundle` - ResourceBundle
 * * `restructuredtext` - reStructuredText
 * * `rexx` - Rexx
 * * `rhtml` - RHTML
 * * `ride` - Ride
 * * `rita` - Rita
 * * `rng-compact` - Relax-NG Compact
 * * `roboconf-graph` - Roboconf Graph
 * * `roboconf-instances` - Roboconf Instances
 * * `robotframework` - RobotFramework
 * * `rql` - RQL
 * * `rsl` - RSL
 * * `ruby` - Ruby
 * * `rust` - Rust
 * * `sarl` - SARL
 * * `sas` - SAS
 * * `sass` - Sass
 * * `savi` - Savi
 * * `scala` - Scala
 * * `scaml` - Scaml
 * * `scdoc` - scdoc
 * * `scheme` - Scheme
 * * `scilab` - Scilab
 * * `scss` - SCSS
 * * `sed` - Sed
 * * `sgf` - SmartGameFormat
 * * `shen` - Shen
 * * `shexc` - ShExC
 * * `sieve` - Sieve
 * * `silver` - Silver
 * * `singularity` - Singularity
 * * `slash` - Slash
 * * `slim` - Slim
 * * `slurm` - Slurm
 * * `smali` - Smali
 * * `smalltalk` - Smalltalk
 * * `smarty` - Smarty
 * * `smithy` - Smithy
 * * `sml` - Standard ML
 * * `snbt` - SNBT
 * * `snobol` - Snobol
 * * `snowball` - Snowball
 * * `solidity` - Solidity
 * * `sophia` - Sophia
 * * `sp` - SourcePawn
 * * `sparql` - SPARQL
 * * `spec` - RPMSpec
 * * `spice` - Spice
 * * `splus` - S
 * * `sql` - SQL
 * * `sql+jinja` - SQL+Jinja
 * * `sqlite3` - sqlite3con
 * * `squidconf` - SquidConf
 * * `srcinfo` - Srcinfo
 * * `ssp` - Scalate Server Page
 * * `stan` - Stan
 * * `stata` - Stata
 * * `supercollider` - SuperCollider
 * * `swift` - Swift
 * * `swig` - SWIG
 * * `systemd` - Systemd
 * * `systemverilog` - systemverilog
 * * `tact` - Tact
 * * `tads3` - TADS 3
 * * `tal` - Tal
 * * `tap` - TAP
 * * `tasm` - TASM
 * * `tcl` - Tcl
 * * `tcsh` - Tcsh
 * * `tcshcon` - Tcsh Session
 * * `tea` - Tea
 * * `teal` - teal
 * * `teratermmacro` - Tera Term macro
 * * `termcap` - Termcap
 * * `terminfo` - Terminfo
 * * `terraform` - Terraform
 * * `tex` - TeX
 * * `text` - Text only
 * * `thrift` - Thrift
 * * `ti` - ThingsDB
 * * `tid` - tiddler
 * * `tlb` - Tl-b
 * * `tls` - TLS Presentation Language
 * * `tnt` - Typographic Number Theory
 * * `todotxt` - Todotxt
 * * `toml` - TOML
 * * `trac-wiki` - MoinMoin/Trac Wiki markup
 * * `trafficscript` - TrafficScript
 * * `treetop` - Treetop
 * * `tsql` - Transact-SQL
 * * `turtle` - Turtle
 * * `twig` - Twig
 * * `typescript` - TypeScript
 * * `typoscript` - TypoScript
 * * `typoscriptcssdata` - TypoScriptCssData
 * * `typoscripthtmldata` - TypoScriptHtmlData
 * * `typst` - Typst
 * * `ucode` - ucode
 * * `ul4` - UL4
 * * `unicon` - Unicon
 * * `unixconfig` - Unix/Linux config files
 * * `urbiscript` - UrbiScript
 * * `urlencoded` - urlencoded
 * * `usd` - USD
 * * `vala` - Vala
 * * `vb.net` - VB.net
 * * `vbscript` - VBScript
 * * `vcl` - VCL
 * * `vclsnippets` - VCLSnippets
 * * `vctreestatus` - VCTreeStatus
 * * `velocity` - Velocity
 * * `verifpal` - Verifpal
 * * `verilog` - verilog
 * * `vgl` - VGL
 * * `vhdl` - vhdl
 * * `vim` - VimL
 * * `visualprolog` - Visual Prolog
 * * `visualprologgrammar` - Visual Prolog Grammar
 * * `vyper` - Vyper
 * * `wast` - WebAssembly
 * * `wdiff` - WDiff
 * * `webidl` - Web IDL
 * * `wgsl` - WebGPU Shading Language
 * * `whiley` - Whiley
 * * `wikitext` - Wikitext
 * * `wowtoc` - World of Warcraft TOC
 * * `wren` - Wren
 * * `x10` - X10
 * * `xml` - XML
 * * `xml+cheetah` - XML+Cheetah
 * * `xml+django` - XML+Django/Jinja
 * * `xml+evoque` - XML+Evoque
 * * `xml+lasso` - XML+Lasso
 * * `xml+mako` - XML+Mako
 * * `xml+myghty` - XML+Myghty
 * * `xml+php` - XML+PHP
 * * `xml+ruby` - XML+Ruby
 * * `xml+smarty` - XML+Smarty
 * * `xml+ul4` - XML+UL4
 * * `xml+velocity` - XML+Velocity
 * * `xorg.conf` - Xorg
 * * `xpp` - X++
 * * `xquery` - XQuery
 * * `xslt` - XSLT
 * * `xtend` - Xtend
 * * `xul+mozpreproc` - XUL+mozpreproc
 * * `yaml` - YAML
 * * `yaml+jinja` - YAML+Jinja
 * * `yang` - YANG
 * * `yara` - YARA
 * * `zeek` - Zeek
 * * `zephir` - Zephir
 * * `zig` - Zig
 * * `zone` - Zone
 * @export
 */
export const LanguageEnum = {
    Abap: 'abap',
    Abnf: 'abnf',
    Actionscript: 'actionscript',
    Actionscript3: 'actionscript3',
    Ada: 'ada',
    Adl: 'adl',
    Agda: 'agda',
    Aheui: 'aheui',
    Alloy: 'alloy',
    Ambienttalk: 'ambienttalk',
    Amdgpu: 'amdgpu',
    Ampl: 'ampl',
    Androidbp: 'androidbp',
    Ansys: 'ansys',
    Antlr: 'antlr',
    AntlrActionscript: 'antlr-actionscript',
    AntlrCpp: 'antlr-cpp',
    AntlrCsharp: 'antlr-csharp',
    AntlrJava: 'antlr-java',
    AntlrObjc: 'antlr-objc',
    AntlrPerl: 'antlr-perl',
    AntlrPython: 'antlr-python',
    AntlrRuby: 'antlr-ruby',
    Apacheconf: 'apacheconf',
    Apl: 'apl',
    Applescript: 'applescript',
    Arduino: 'arduino',
    Arrow: 'arrow',
    Arturo: 'arturo',
    Asc: 'asc',
    Asn1: 'asn1',
    Aspectj: 'aspectj',
    AspxCs: 'aspx-cs',
    AspxVb: 'aspx-vb',
    Asymptote: 'asymptote',
    Augeas: 'augeas',
    Autohotkey: 'autohotkey',
    Autoit: 'autoit',
    Awk: 'awk',
    Bare: 'bare',
    Basemake: 'basemake',
    Bash: 'bash',
    Batch: 'batch',
    Bbcbasic: 'bbcbasic',
    Bbcode: 'bbcode',
    Bc: 'bc',
    Bdd: 'bdd',
    Befunge: 'befunge',
    Berry: 'berry',
    Bibtex: 'bibtex',
    Blitzbasic: 'blitzbasic',
    Blitzmax: 'blitzmax',
    Blueprint: 'blueprint',
    Bnf: 'bnf',
    Boa: 'boa',
    Boo: 'boo',
    Boogie: 'boogie',
    Bqn: 'bqn',
    Brainfuck: 'brainfuck',
    Bst: 'bst',
    Bugs: 'bugs',
    C: 'c',
    CObjdump: 'c-objdump',
    Ca65: 'ca65',
    Cadl: 'cadl',
    Camkes: 'camkes',
    Capdl: 'capdl',
    Capnp: 'capnp',
    Carbon: 'carbon',
    Cbmbas: 'cbmbas',
    Cddl: 'cddl',
    Ceylon: 'ceylon',
    Cfc: 'cfc',
    Cfengine3: 'cfengine3',
    Cfm: 'cfm',
    Cfs: 'cfs',
    Chaiscript: 'chaiscript',
    Chapel: 'chapel',
    Charmci: 'charmci',
    Cheetah: 'cheetah',
    Cirru: 'cirru',
    Clay: 'clay',
    Clean: 'clean',
    Clojure: 'clojure',
    Clojurescript: 'clojurescript',
    Cmake: 'cmake',
    Cobol: 'cobol',
    Cobolfree: 'cobolfree',
    Coffeescript: 'coffeescript',
    Comal: 'comal',
    CommonLisp: 'common-lisp',
    Componentpascal: 'componentpascal',
    Console: 'console',
    Coq: 'coq',
    Cplint: 'cplint',
    Cpp: 'cpp',
    CppObjdump: 'cpp-objdump',
    Cpsa: 'cpsa',
    Cr: 'cr',
    Crmsh: 'crmsh',
    Croc: 'croc',
    Cryptol: 'cryptol',
    Csharp: 'csharp',
    Csound: 'csound',
    CsoundDocument: 'csound-document',
    CsoundScore: 'csound-score',
    Css: 'css',
    Cssdjango: 'css+django',
    Cssgenshitext: 'css+genshitext',
    Csslasso: 'css+lasso',
    Cssmako: 'css+mako',
    Cssmozpreproc: 'css+mozpreproc',
    Cssmyghty: 'css+myghty',
    Cssphp: 'css+php',
    Cssruby: 'css+ruby',
    Csssmarty: 'css+smarty',
    Cssul4: 'css+ul4',
    Cuda: 'cuda',
    Cypher: 'cypher',
    Cython: 'cython',
    D: 'd',
    DObjdump: 'd-objdump',
    Dart: 'dart',
    Dasm16: 'dasm16',
    Dax: 'dax',
    Debcontrol: 'debcontrol',
    Debsources: 'debsources',
    Delphi: 'delphi',
    Desktop: 'desktop',
    Devicetree: 'devicetree',
    Dg: 'dg',
    Diff: 'diff',
    Django: 'django',
    Docker: 'docker',
    Doscon: 'doscon',
    Dpatch: 'dpatch',
    Dtd: 'dtd',
    Duel: 'duel',
    Dylan: 'dylan',
    DylanConsole: 'dylan-console',
    DylanLid: 'dylan-lid',
    EarlGrey: 'earl-grey',
    Easytrieve: 'easytrieve',
    Ebnf: 'ebnf',
    Ec: 'ec',
    Ecl: 'ecl',
    Eiffel: 'eiffel',
    Elixir: 'elixir',
    Elm: 'elm',
    Elpi: 'elpi',
    EmacsLisp: 'emacs-lisp',
    Email: 'email',
    Erb: 'erb',
    Erl: 'erl',
    Erlang: 'erlang',
    Evoque: 'evoque',
    Execline: 'execline',
    Extempore: 'extempore',
    Ezhil: 'ezhil',
    Factor: 'factor',
    Fan: 'fan',
    Fancy: 'fancy',
    Felix: 'felix',
    Fennel: 'fennel',
    Fift: 'fift',
    Fish: 'fish',
    Flatline: 'flatline',
    Floscript: 'floscript',
    Forth: 'forth',
    Fortran: 'fortran',
    Fortranfixed: 'fortranfixed',
    Foxpro: 'foxpro',
    Freefem: 'freefem',
    Fsharp: 'fsharp',
    Fstar: 'fstar',
    Func: 'func',
    Futhark: 'futhark',
    Gap: 'gap',
    GapConsole: 'gap-console',
    Gas: 'gas',
    Gcode: 'gcode',
    Gdscript: 'gdscript',
    Genshi: 'genshi',
    Genshitext: 'genshitext',
    Gherkin: 'gherkin',
    Glsl: 'glsl',
    Gnuplot: 'gnuplot',
    Go: 'go',
    Golo: 'golo',
    GooddataCl: 'gooddata-cl',
    Gosu: 'gosu',
    Graphql: 'graphql',
    Graphviz: 'graphviz',
    Groff: 'groff',
    Groovy: 'groovy',
    Gsql: 'gsql',
    Gst: 'gst',
    Haml: 'haml',
    Handlebars: 'handlebars',
    Haskell: 'haskell',
    Haxe: 'haxe',
    Haxeml: 'haxeml',
    Hexdump: 'hexdump',
    Hlsl: 'hlsl',
    Hsail: 'hsail',
    Hspec: 'hspec',
    Html: 'html',
    Htmlcheetah: 'html+cheetah',
    Htmldjango: 'html+django',
    Htmlevoque: 'html+evoque',
    Htmlgenshi: 'html+genshi',
    Htmlhandlebars: 'html+handlebars',
    Htmllasso: 'html+lasso',
    Htmlmako: 'html+mako',
    Htmlmyghty: 'html+myghty',
    Htmlng2: 'html+ng2',
    Htmlphp: 'html+php',
    Htmlsmarty: 'html+smarty',
    Htmltwig: 'html+twig',
    Htmlul4: 'html+ul4',
    Htmlvelocity: 'html+velocity',
    Http: 'http',
    Hybris: 'hybris',
    Hylang: 'hylang',
    I6t: 'i6t',
    Icon: 'icon',
    Idl: 'idl',
    Idris: 'idris',
    Iex: 'iex',
    Igor: 'igor',
    Inform6: 'inform6',
    Inform7: 'inform7',
    Ini: 'ini',
    Io: 'io',
    Ioke: 'ioke',
    Irc: 'irc',
    Isabelle: 'isabelle',
    J: 'j',
    Jags: 'jags',
    Janet: 'janet',
    Jasmin: 'jasmin',
    Java: 'java',
    Javascript: 'javascript',
    Javascriptcheetah: 'javascript+cheetah',
    Javascriptdjango: 'javascript+django',
    Javascriptlasso: 'javascript+lasso',
    Javascriptmako: 'javascript+mako',
    Javascriptmozpreproc: 'javascript+mozpreproc',
    Javascriptmyghty: 'javascript+myghty',
    Javascriptphp: 'javascript+php',
    Javascriptruby: 'javascript+ruby',
    Javascriptsmarty: 'javascript+smarty',
    Jcl: 'jcl',
    Jlcon: 'jlcon',
    Jmespath: 'jmespath',
    Jsgenshitext: 'js+genshitext',
    Jsul4: 'js+ul4',
    Jsgf: 'jsgf',
    Jslt: 'jslt',
    Json: 'json',
    Jsonld: 'jsonld',
    Jsonnet: 'jsonnet',
    Jsp: 'jsp',
    Jsx: 'jsx',
    Julia: 'julia',
    Juttle: 'juttle',
    K: 'k',
    Kal: 'kal',
    Kconfig: 'kconfig',
    Kmsg: 'kmsg',
    Koka: 'koka',
    Kotlin: 'kotlin',
    Kql: 'kql',
    Kuin: 'kuin',
    Lasso: 'lasso',
    Ldapconf: 'ldapconf',
    Ldif: 'ldif',
    Lean: 'lean',
    Lean4: 'lean4',
    Less: 'less',
    Lighttpd: 'lighttpd',
    Lilypond: 'lilypond',
    Limbo: 'limbo',
    Liquid: 'liquid',
    LiterateAgda: 'literate-agda',
    LiterateCryptol: 'literate-cryptol',
    LiterateHaskell: 'literate-haskell',
    LiterateIdris: 'literate-idris',
    Livescript: 'livescript',
    Llvm: 'llvm',
    LlvmMir: 'llvm-mir',
    LlvmMirBody: 'llvm-mir-body',
    Logos: 'logos',
    Logtalk: 'logtalk',
    Lsl: 'lsl',
    Lua: 'lua',
    Luau: 'luau',
    Macaulay2: 'macaulay2',
    Make: 'make',
    Mako: 'mako',
    Maql: 'maql',
    Markdown: 'markdown',
    Mask: 'mask',
    Mason: 'mason',
    Mathematica: 'mathematica',
    Matlab: 'matlab',
    Matlabsession: 'matlabsession',
    Maxima: 'maxima',
    Mcfunction: 'mcfunction',
    Mcschema: 'mcschema',
    Meson: 'meson',
    Mime: 'mime',
    Minid: 'minid',
    Miniscript: 'miniscript',
    Mips: 'mips',
    Modelica: 'modelica',
    Modula2: 'modula2',
    Mojo: 'mojo',
    Monkey: 'monkey',
    Monte: 'monte',
    Moocode: 'moocode',
    Moonscript: 'moonscript',
    Mosel: 'mosel',
    Mozhashpreproc: 'mozhashpreproc',
    Mozpercentpreproc: 'mozpercentpreproc',
    Mql: 'mql',
    Mscgen: 'mscgen',
    Mupad: 'mupad',
    Mxml: 'mxml',
    Myghty: 'myghty',
    Mysql: 'mysql',
    Nasm: 'nasm',
    Ncl: 'ncl',
    Nemerle: 'nemerle',
    Nesc: 'nesc',
    Nestedtext: 'nestedtext',
    Newlisp: 'newlisp',
    Newspeak: 'newspeak',
    Ng2: 'ng2',
    Nginx: 'nginx',
    Nimrod: 'nimrod',
    Nit: 'nit',
    Nixos: 'nixos',
    Nodejsrepl: 'nodejsrepl',
    Notmuch: 'notmuch',
    Nsis: 'nsis',
    Numpy: 'numpy',
    Nusmv: 'nusmv',
    Objdump: 'objdump',
    ObjdumpNasm: 'objdump-nasm',
    ObjectiveC: 'objective-c',
    ObjectiveC2: 'objective-c++',
    ObjectiveJ: 'objective-j',
    Ocaml: 'ocaml',
    Octave: 'octave',
    Odin: 'odin',
    OmgIdl: 'omg-idl',
    Ooc: 'ooc',
    Opa: 'opa',
    Openedge: 'openedge',
    Openscad: 'openscad',
    Org: 'org',
    Output: 'output',
    Pacmanconf: 'pacmanconf',
    Pan: 'pan',
    Parasail: 'parasail',
    Pawn: 'pawn',
    Peg: 'peg',
    Perl: 'perl',
    Perl6: 'perl6',
    Phix: 'phix',
    Php: 'php',
    Pig: 'pig',
    Pike: 'pike',
    Pkgconfig: 'pkgconfig',
    Plpgsql: 'plpgsql',
    Pointless: 'pointless',
    Pony: 'pony',
    Portugol: 'portugol',
    PostgresExplain: 'postgres-explain',
    Postgresql: 'postgresql',
    Postscript: 'postscript',
    Pot: 'pot',
    Pov: 'pov',
    Powershell: 'powershell',
    Praat: 'praat',
    Procfile: 'procfile',
    Prolog: 'prolog',
    Promela: 'promela',
    Promql: 'promql',
    Properties: 'properties',
    Protobuf: 'protobuf',
    Prql: 'prql',
    Psql: 'psql',
    Psysh: 'psysh',
    Ptx: 'ptx',
    Pug: 'pug',
    Puppet: 'puppet',
    PwshSession: 'pwsh-session',
    Pyul4: 'py+ul4',
    Py2tb: 'py2tb',
    Pycon: 'pycon',
    Pypylog: 'pypylog',
    Pytb: 'pytb',
    Python: 'python',
    Python2: 'python2',
    Q: 'q',
    Qbasic: 'qbasic',
    Qlik: 'qlik',
    Qml: 'qml',
    Qvto: 'qvto',
    Racket: 'racket',
    Ragel: 'ragel',
    RagelC: 'ragel-c',
    RagelCpp: 'ragel-cpp',
    RagelD: 'ragel-d',
    RagelEm: 'ragel-em',
    RagelJava: 'ragel-java',
    RagelObjc: 'ragel-objc',
    RagelRuby: 'ragel-ruby',
    Rbcon: 'rbcon',
    Rconsole: 'rconsole',
    Rd: 'rd',
    Reasonml: 'reasonml',
    Rebol: 'rebol',
    Red: 'red',
    Redcode: 'redcode',
    Registry: 'registry',
    Resourcebundle: 'resourcebundle',
    Restructuredtext: 'restructuredtext',
    Rexx: 'rexx',
    Rhtml: 'rhtml',
    Ride: 'ride',
    Rita: 'rita',
    RngCompact: 'rng-compact',
    RoboconfGraph: 'roboconf-graph',
    RoboconfInstances: 'roboconf-instances',
    Robotframework: 'robotframework',
    Rql: 'rql',
    Rsl: 'rsl',
    Ruby: 'ruby',
    Rust: 'rust',
    Sarl: 'sarl',
    Sas: 'sas',
    Sass: 'sass',
    Savi: 'savi',
    Scala: 'scala',
    Scaml: 'scaml',
    Scdoc: 'scdoc',
    Scheme: 'scheme',
    Scilab: 'scilab',
    Scss: 'scss',
    Sed: 'sed',
    Sgf: 'sgf',
    Shen: 'shen',
    Shexc: 'shexc',
    Sieve: 'sieve',
    Silver: 'silver',
    Singularity: 'singularity',
    Slash: 'slash',
    Slim: 'slim',
    Slurm: 'slurm',
    Smali: 'smali',
    Smalltalk: 'smalltalk',
    Smarty: 'smarty',
    Smithy: 'smithy',
    Sml: 'sml',
    Snbt: 'snbt',
    Snobol: 'snobol',
    Snowball: 'snowball',
    Solidity: 'solidity',
    Sophia: 'sophia',
    Sp: 'sp',
    Sparql: 'sparql',
    Spec: 'spec',
    Spice: 'spice',
    Splus: 'splus',
    Sql: 'sql',
    Sqljinja: 'sql+jinja',
    Sqlite3: 'sqlite3',
    Squidconf: 'squidconf',
    Srcinfo: 'srcinfo',
    Ssp: 'ssp',
    Stan: 'stan',
    Stata: 'stata',
    Supercollider: 'supercollider',
    Swift: 'swift',
    Swig: 'swig',
    Systemd: 'systemd',
    Systemverilog: 'systemverilog',
    Tact: 'tact',
    Tads3: 'tads3',
    Tal: 'tal',
    Tap: 'tap',
    Tasm: 'tasm',
    Tcl: 'tcl',
    Tcsh: 'tcsh',
    Tcshcon: 'tcshcon',
    Tea: 'tea',
    Teal: 'teal',
    Teratermmacro: 'teratermmacro',
    Termcap: 'termcap',
    Terminfo: 'terminfo',
    Terraform: 'terraform',
    Tex: 'tex',
    Text: 'text',
    Thrift: 'thrift',
    Ti: 'ti',
    Tid: 'tid',
    Tlb: 'tlb',
    Tls: 'tls',
    Tnt: 'tnt',
    Todotxt: 'todotxt',
    Toml: 'toml',
    TracWiki: 'trac-wiki',
    Trafficscript: 'trafficscript',
    Treetop: 'treetop',
    Tsql: 'tsql',
    Turtle: 'turtle',
    Twig: 'twig',
    Typescript: 'typescript',
    Typoscript: 'typoscript',
    Typoscriptcssdata: 'typoscriptcssdata',
    Typoscripthtmldata: 'typoscripthtmldata',
    Typst: 'typst',
    Ucode: 'ucode',
    Ul4: 'ul4',
    Unicon: 'unicon',
    Unixconfig: 'unixconfig',
    Urbiscript: 'urbiscript',
    Urlencoded: 'urlencoded',
    Usd: 'usd',
    Vala: 'vala',
    VbNet: 'vb.net',
    Vbscript: 'vbscript',
    Vcl: 'vcl',
    Vclsnippets: 'vclsnippets',
    Vctreestatus: 'vctreestatus',
    Velocity: 'velocity',
    Verifpal: 'verifpal',
    Verilog: 'verilog',
    Vgl: 'vgl',
    Vhdl: 'vhdl',
    Vim: 'vim',
    Visualprolog: 'visualprolog',
    Visualprologgrammar: 'visualprologgrammar',
    Vyper: 'vyper',
    Wast: 'wast',
    Wdiff: 'wdiff',
    Webidl: 'webidl',
    Wgsl: 'wgsl',
    Whiley: 'whiley',
    Wikitext: 'wikitext',
    Wowtoc: 'wowtoc',
    Wren: 'wren',
    X10: 'x10',
    Xml: 'xml',
    Xmlcheetah: 'xml+cheetah',
    Xmldjango: 'xml+django',
    Xmlevoque: 'xml+evoque',
    Xmllasso: 'xml+lasso',
    Xmlmako: 'xml+mako',
    Xmlmyghty: 'xml+myghty',
    Xmlphp: 'xml+php',
    Xmlruby: 'xml+ruby',
    Xmlsmarty: 'xml+smarty',
    Xmlul4: 'xml+ul4',
    Xmlvelocity: 'xml+velocity',
    XorgConf: 'xorg.conf',
    Xpp: 'xpp',
    Xquery: 'xquery',
    Xslt: 'xslt',
    Xtend: 'xtend',
    Xulmozpreproc: 'xul+mozpreproc',
    Yaml: 'yaml',
    Yamljinja: 'yaml+jinja',
    Yang: 'yang',
    Yara: 'yara',
    Zeek: 'zeek',
    Zephir: 'zephir',
    Zig: 'zig',
    Zone: 'zone'
} as const;
export type LanguageEnum = typeof LanguageEnum[keyof typeof LanguageEnum];


export function instanceOfLanguageEnum(value: any): boolean {
    for (const key in LanguageEnum) {
        if (Object.prototype.hasOwnProperty.call(LanguageEnum, key)) {
            if (LanguageEnum[key as keyof typeof LanguageEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LanguageEnumFromJSON(json: any): LanguageEnum {
    return LanguageEnumFromJSONTyped(json, false);
}

export function LanguageEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguageEnum {
    return json as LanguageEnum;
}

export function LanguageEnumToJSON(value?: LanguageEnum | null): any {
    return value as any;
}

