/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Snippet } from './Snippet';
import {
    SnippetFromJSON,
    SnippetFromJSONTyped,
    SnippetToJSON,
} from './Snippet';

/**
 * 
 * @export
 * @interface PaginatedSnippetList
 */
export interface PaginatedSnippetList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSnippetList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSnippetList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSnippetList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Snippet>}
     * @memberof PaginatedSnippetList
     */
    results: Array<Snippet>;
}

/**
 * Check if a given object implements the PaginatedSnippetList interface.
 */
export function instanceOfPaginatedSnippetList(value: object): value is PaginatedSnippetList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedSnippetListFromJSON(json: any): PaginatedSnippetList {
    return PaginatedSnippetListFromJSONTyped(json, false);
}

export function PaginatedSnippetListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSnippetList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(SnippetFromJSON)),
    };
}

export function PaginatedSnippetListToJSON(value?: PaginatedSnippetList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(SnippetToJSON)),
    };
}

