/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedChoice
 */
export interface PatchedChoice {
    /**
     * 
     * @type {number}
     * @memberof PatchedChoice
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedChoice
     */
    choiceText?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedChoice
     */
    votes?: number;
}

/**
 * Check if a given object implements the PatchedChoice interface.
 */
export function instanceOfPatchedChoice(value: object): value is PatchedChoice {
    return true;
}

export function PatchedChoiceFromJSON(json: any): PatchedChoice {
    return PatchedChoiceFromJSONTyped(json, false);
}

export function PatchedChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedChoice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'choiceText': json['choice_text'] == null ? undefined : json['choice_text'],
        'votes': json['votes'] == null ? undefined : json['votes'],
    };
}

export function PatchedChoiceToJSON(value?: Omit<PatchedChoice, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'choice_text': value['choiceText'],
        'votes': value['votes'],
    };
}

