/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StyleEnum } from './StyleEnum';
import {
    StyleEnumFromJSON,
    StyleEnumFromJSONTyped,
    StyleEnumToJSON,
} from './StyleEnum';
import type { LanguageEnum } from './LanguageEnum';
import {
    LanguageEnumFromJSON,
    LanguageEnumFromJSONTyped,
    LanguageEnumToJSON,
} from './LanguageEnum';

/**
 * 
 * @export
 * @interface Snippet
 */
export interface Snippet {
    /**
     * 
     * @type {number}
     * @memberof Snippet
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof Snippet
     */
    readonly created: Date;
    /**
     * 
     * @type {string}
     * @memberof Snippet
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Snippet
     */
    code: string;
    /**
     * 
     * @type {boolean}
     * @memberof Snippet
     */
    linenos?: boolean;
    /**
     * 
     * @type {LanguageEnum}
     * @memberof Snippet
     */
    language?: LanguageEnum;
    /**
     * 
     * @type {StyleEnum}
     * @memberof Snippet
     */
    style?: StyleEnum;
}



/**
 * Check if a given object implements the Snippet interface.
 */
export function instanceOfSnippet(value: object): value is Snippet {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function SnippetFromJSON(json: any): Snippet {
    return SnippetFromJSONTyped(json, false);
}

export function SnippetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Snippet {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': (new Date(json['created'])),
        'title': json['title'] == null ? undefined : json['title'],
        'code': json['code'],
        'linenos': json['linenos'] == null ? undefined : json['linenos'],
        'language': json['language'] == null ? undefined : LanguageEnumFromJSON(json['language']),
        'style': json['style'] == null ? undefined : StyleEnumFromJSON(json['style']),
    };
}

export function SnippetToJSON(value?: Omit<Snippet, 'id'|'created'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'code': value['code'],
        'linenos': value['linenos'],
        'language': LanguageEnumToJSON(value['language']),
        'style': StyleEnumToJSON(value['style']),
    };
}

